---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new, new features, features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.12.0 에는 새로운 향상 기능이 포함되어 있습니다. 
---
= Cloud Volumes ONTAP 9.12.0 의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.0 에는 새로운 향상 기능이 포함되어 있습니다.

최신 버전의 BlueXP에는 추가 기능 및 향상된 기능이 도입되었습니다.  https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["BlueXP 릴리스 정보"^]자세한 내용은 를 참조하십시오.



== 9.12.0 P1(2022년 12월 15일)

Cloud Volumes ONTAP 9.12.0 P1은 현재 AWS 및 Google Cloud에서 사용할 수 있습니다. 이 릴리즈에는 다음과 같은 새로운 기능이 포함되어 있습니다.



=== AWS에서 m6id.32xlarge 지원

Cloud Volumes ONTAP는 이제 AWS에서 m6id.32xlarge EC2 인스턴스 유형으로 지원됩니다.

자세한 내용은 을 link:reference-configs-aws.html["지원되는 구성 페이지"]참조하십시오.



== 노트 업그레이드

이 릴리스 업그레이드에 대한 자세한 내용은 이 노트를 참조하십시오.



=== 업그레이드 방법

Cloud Volumes ONTAP 업그레이드는 BlueXP에서 완료해야 합니다. System Manager 또는 CLI를 사용하여 Cloud Volumes ONTAP를 업그레이드해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 줄 수 있습니다.

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXP에서 알림을 받을 때 업그레이드하는 방법에 대해 알아봅니다"^]..



=== 지원되는 업그레이드 경로입니다

9.11.1 릴리스에서 Cloud Volumes ONTAP 9.12.0으로 업그레이드할 수 있습니다. BlueXP에서 해당 Cloud Volumes ONTAP 시스템을 이 릴리즈로 업그레이드하라는 메시지가 표시됩니다.



=== 커넥터의 필수 버전입니다

새 Cloud Volumes ONTAP 9.12.0 시스템을 배포하고 기존 시스템을 이 릴리스로 업그레이드하려면 BlueXP  커넥터가 버전 3.9.24 이상을 실행해야 합니다.


TIP: Connector의 자동 업그레이드는 기본적으로 활성화되어 있으므로 최신 버전을 실행해야 합니다.



=== 알아 보십시오

* 단일 노드 시스템을 업그레이드하면 시스템이 최대 25분 동안 오프라인 상태로 전환되고 이 동안 I/O가 중단됩니다.
* HA 2노드 업그레이드는 무중단으로 I/O를 업그레이드할 수 있으며 이 무중단 업그레이드 프로세스 중에 각 노드가 동시 업그레이드되어 클라이언트에 I/O를 계속 제공합니다.




=== C4, M4 및 R4 EC2 인스턴스 유형으로 AWS에서 업그레이드

AWS에서는 새로운 Cloud Volumes ONTAP 구축에서 C4, M4 및 R4 EC2 인스턴스 유형이 더 이상 지원되지 않습니다. C4, M4 또는 R4 인스턴스 유형에서 실행 중인 기존 시스템이 있는 경우 C5, M5 또는 R5 인스턴스 제품군의 인스턴스 유형으로 변경해야 합니다. 인스턴스 유형을 변경할 수 없는 경우 업그레이드하기 전에 향상된 네트워킹을 활성화해야 합니다.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["AWS에서 C4, M4 및 R4 EC2 인스턴스 유형으로 업그레이드하는 방법을 알아보십시오"^].. link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP의 EC2 인스턴스 유형을 변경하는 방법에 대해 알아보십시오"^]..

link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp 지원"^]이러한 인스턴스 유형에 대한 공급 중지 및 지원에 대한 자세한 내용은 을 참조하십시오.
